merge into Physician_Compare.Test as cm
using Physician_Compare.Test_stagging as cs
on (cm.pac_id = cs.pac_id)
when matched and cm.city <> cs.city and cm.state <> cs.state 
then update set cm.city =cs.city, cm.flag='N', cm.state=cs.state
when not matched 
then insert 
(NPI,
PAC_ID,
Professional_Enrollment_ID,
Last_Name,
First_Name,
Middle_Name,
Suffix,
Gender,
Credential,
Medical_school_name,
Graduation_year,
Primary_specialty,
Secondary_specialty_1,
Secondary_specialty_2,
Secondary_specialty_3,
Secondary_specialty_4,
All_secondary_specialties,
Organization_legal_name,
Group_Practice_PAC_ID,
Number_of_Group_Practice_members,
Line_1_Street_Address,
Line_2_Street_Address,
Marker_of_address_line_2_suppression,
City,
State,
Zip_Code,
Phone_Number,
Hospital_affiliation_CCN_1,
Hospital_affiliation_LBN_1,
Hospital_affiliation_CCN_2,
Hospital_affiliation_LBN_2,
Hospital_affiliation_CCN_3,
Hospital_affiliation_LBN_3,
Hospital_affiliation_CCN_4,
Hospital_affiliation_LBN_4,
Hospital_affiliation_CCN_5,
Hospital_affiliation_LBN_5,
Professional_accepts_Medicare_Assignment,
Reported_Quality_Measures,
Used_electronic_health_records,
Committed_to_heart_health_through_the_Million_Hearts___initiative_ ,
flag) 
values
(
cs.NPI,
cs.PAC_ID,
cs.Professional_Enrollment_ID,
cs.Last_Name,
cs.First_Name,
cs.Middle_Name,
cs.Suffix,
cs.Gender,
cs.Credential,
cs.Medical_school_name,
cs.Graduation_year,
cs.Primary_specialty,
cs.Secondary_specialty_1,
cs.Secondary_specialty_2,
cs.Secondary_specialty_3,
cs.Secondary_specialty_4,
cs.All_secondary_specialties,
cs.Organization_legal_name,
cs.Group_Practice_PAC_ID,
cs.Number_of_Group_Practice_members,
cs.Line_1_Street_Address,
cs.Line_2_Street_Address,
cs.Marker_of_address_line_2_suppression,
cs.City,
cs.State,
cs.Zip_Code,
cs.Phone_Number,
cs.Hospital_affiliation_CCN_1,
cs.Hospital_affiliation_LBN_1,
cs.Hospital_affiliation_CCN_2,
cs.Hospital_affiliation_LBN_2,
cs.Hospital_affiliation_CCN_3,
cs.Hospital_affiliation_LBN_3,
cs.Hospital_affiliation_CCN_4,
cs.Hospital_affiliation_LBN_4,
cs.Hospital_affiliation_CCN_5,
cs.Hospital_affiliation_LBN_5,
cs.Professional_accepts_Medicare_Assignment,
cs.Reported_Quality_Measures,
cs.Used_electronic_health_records,
cs.Committed_to_heart_health_through_the_Million_Hearts___initiative_ , 'N');